Kisumu_localities <- new("SpatialPointsDataFrame", data = structure(list(Northing = c(-0.18358, 
                                                                            -0.147, -0.18822, -0.22762, -0.27578), Easting = c(34.81306, 
                                                                                                                               34.93436, 34.89974, 34.95432, 34.97058), SchemeName = structure(c(4L, 
                                                                                                                                                                                                 1L, 2L, 5L, 3L), .Label = c("Ahero NIB", "Ahero out-growers", 
                                                                                                                                                                                                                             "Jimo", "Rabour", "Rariada, Awach"), class = "factor"), SchemeType = structure(c(4L, 
                                                                                                                                                                                                                                                                                                              5L, 1L, 2L, 3L), .Label = c("FBFS type 1", "FBFS type 2", "FBFS type 3", 
                                                                                                                                                                                                                                                                                                                                          "irrigation type 1", "irrigation type 2"), class = "factor")), class = "data.frame", row.names = c(NA, 
                                                                                                                                                                                                                                                                                                                                                                                                                                             -5L)), coords.nrs = numeric(0), coords = structure(c(34.81306, 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  34.93436, 34.89974, 34.95432, 34.97058, -0.18358, -0.147, -0.18822, 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  -0.22762, -0.27578), .Dim = c(5L, 2L), .Dimnames = list(NULL, 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          c("coords.x1", "coords.x2"))), bbox = structure(c(34.81306, 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            -0.27578, 34.97058, -0.147), .Dim = c(2L, 2L), .Dimnames = list(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              c("coords.x1", "coords.x2"), c("min", "max"))), proj4string = new("CRS", 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                projargs = "+proj=longlat +datum=WGS84 +no_defs +ellps=WGS84 +towgs84=0,0,0"))


Kisumu_localities$SchemeName_short <- c('Rabour', 'Ahero 1', 'Ahero 2', 'Rariada', 'Jimo')
# reading and checking shapefiles
# Schemes <- readOGR(dsn = getwd(), 'Liman_ethiopia_scheme_studyArea')
Tigray_localities <- new("SpatialPointsDataFrame", data = structure(list(Northing = c(1379013, 
                                                                            1414903, 1361026.08), Easting = c(565792, 565082, 568271.85), 
                                                               SchemeName = structure(c(1L, 3L, 2L), .Label = c("Dayu (Gerjele)", 
                                                                                                                "Harosha (Tumuga)", "Tsige'a (Guguf)"), class = "factor"), 
                                                               SchemeType = structure(c(2L, 1L, 3L), .Label = c("Improved", 
                                                                                                                "Modern", "Traditional"), class = "factor"), DesignedCo = c(320, 
                                                                                                                                                                            NA, 188), StatusComm = structure(c(1L, 2L, 2L), .Label = c("Decreasing", 
                                                                                                                                                                                                                                       "Increasing"), class = "factor")), class = "data.frame", row.names = c(NA, 
                                                                                                                                                                                                                                                                                                              -3L)), coords.nrs = numeric(0), coords = structure(c(565792, 
                                                                                                                                                                                                                                                                                                                                                                   565082, 568271.85, 1379013, 1414903, 1361026.08), .Dim = 3:2, .Dimnames = list(
                                                                                                                                                                                                                                                                                                                                                                     NULL, c("coords.x1", "coords.x2"))), bbox = structure(c(565082, 
                                                                                                                                                                                                                                                                                                                                                                                                                             1361026.08, 568271.85, 1414903), .Dim = c(2L, 2L), .Dimnames = list(
                                                                                                                                                                                                                                                                                                                                                                                                                               c("coords.x1", "coords.x2"), c("min", "max"))), proj4string = new("CRS", 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 projargs = "+proj=utm +zone=37 +datum=WGS84 +units=m +no_defs +ellps=WGS84 +towgs84=0,0,0"))

Tigray_localities <- spTransform(Tigray_localities, CRS("+proj=longlat +datum=WGS84"))
Tigray_localities$SchemeName_short <- c('Dayu', "Tsige'a", "Harosha")
